-- Fuentes y targets de rastreo por defecto. Después de esto, la API es la autoridad:
-- `INSERT OR IGNORE` no pisa nada que ya exista con la misma clave.
INSERT OR IGNORE INTO scrape_sources (key, name, base_url, search_url_template, listing_url, access, notes, config, is_active) VALUES ('flexicar', 'Flexicar', 'https://www.flexicar.es', 'https://www.flexicar.es/{make_slug}/{model_slug}/segunda-mano/', NULL, 'fetch', 'El HTML trae __NEXT_DATA__. Contrastar el precio de la tarjeta con la ficha y usar el precio de contado de la ficha.', '{"extractor":"scrapers/flexicar.py","vehicles_api_url":"https://services.flexicar.es/api/v1/vehicles","make_slug_aliases":{"mercedes":"mercedes-benz"},"_defaults_version":2}', 1);
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_sources (key, name, base_url, search_url_template, listing_url, access, notes, config, is_active) VALUES ('coches.net', 'Coches.net', 'https://www.coches.net', 'https://www.coches.net/search/?MakeIds%5B0%5D={make_id}&ModelIds%5B0%5D={model_id}', NULL, 'playwright', 'Listado público renderizado con JavaScript. Usar Playwright y navegador real como fallback, siempre en modo de solo lectura.', '{"extractor":"scrapers/cochesnet.py","card_selector":".mt-ListAds-item.mt-CardAd","_defaults_version":1}', 1);
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_sources (key, name, base_url, search_url_template, listing_url, access, notes, config, is_active) VALUES ('ocasionplus', 'OcasionPlus', 'https://www.ocasionplus.com', NULL, NULL, 'playwright', 'Descubrir la URL desde la interfaz pública y persistirla en el target. Usar navegador real como fallback y no superar tres páginas.', '{"extractor":"scrapers/ocasionplus.py","card_hint":"atributos data-test","_defaults_version":1}', 1);
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_sources (key, name, base_url, search_url_template, listing_url, access, notes, config, is_active) VALUES ('irurimotor', 'Iruri Motor', 'https://irurimotor.com', 'https://irurimotor.com/wp-json/vehica/v1/cars?marca={make_slug}', 'https://irurimotor.com/todoterrenos-coches-de-segunda-mano-y-ocasion-sunbilla-navarra/?type=todoterrenos', 'fetch', 'El endpoint público de Vehica entrega el inventario en JSON.', '{"extractor":"scrapers/irurimotor.py","_defaults_version":1}', 1);
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_sources (key, name, base_url, search_url_template, listing_url, access, notes, config, is_active) VALUES ('compramostucoche', 'Compramos Tu Coche', 'https://www.compramostucoche.es', 'https://www.compramostucoche.es/comprar-coche/?brand={brand}&model={brand}.{model_token}&sort=STANDARD_PRICE_ASC', 'https://www.compramostucoche.es/comprar-coche/', 'fetch', 'Listado renderizado en servidor; las clases CSS llevan hash y solo son estables los atributos data-qa-selector. Los tokens de marca y modelo no son los que muestra la interfaz: brand usa guion bajo (MERCEDES_BENZ) y model usa el nombre interno en aleman (A-KLASSE, PAJERO). Un token invalido NO da error: devuelve 200 con el catalogo sin filtrar, asi que hay que exigir el chip filter-item-vehicle antes de dar el listado por bueno. Cada carroceria es un modelo aparte y no se pueden combinar en una URL, por eso el target lleva model_tokens.', '{"extractor":"scrapers/compramostucoche.py","card_selector":"[data-qa-selector=\"ad-item\"]","assert_selector":"[data-qa-selector=\"filter-item-vehicle\"]","page_size":10,"seller_name":"Autohero","_defaults_version":1}', 1);
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_sources (key, name, base_url, search_url_template, listing_url, access, notes, config, is_active) VALUES ('quadis', 'Quadis', 'https://www.quadis.es', 'https://www.quadis.es/coches/{make_slug}/{model_slug}', 'https://www.quadis.es/coches', 'browser', 'El listado público renderiza tarjetas .car-card. robots.txt bloquea las URLs con query string; usar navegador para los targets que necesiten IDs.', '{"extractor":"scrapers/quadis.py","card_selector":".car-card","make_slug_aliases":{"mercedes":"mercedes-benz"},"_defaults_version":1}', 1);
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'audi|a4 allroad quattro', 'Audi', 'A4 Allroad quattro', 15, NULL, '{"make_slug":"audi","model_slug":"a4-allroad-quattro"}', 1 FROM scrape_sources WHERE key = 'flexicar';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'audi|a4 allroad quattro', 'Audi', 'A4 Allroad quattro', 15, NULL, '{"make_id":4,"model_id":925}', 1 FROM scrape_sources WHERE key = 'coches.net';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'mercedes|clase a', 'Mercedes', 'Clase A', 15, NULL, '{"make_slug":"mercedes-benz","model_slug":"clase-a"}', 1 FROM scrape_sources WHERE key = 'flexicar';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'mercedes|clase a', 'Mercedes', 'Clase A', 15, NULL, '{"make_id":28,"model_id":275}', 1 FROM scrape_sources WHERE key = 'coches.net';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'mercedes|clase a', 'Mercedes', 'Clase A', 15, NULL, '{}', 1 FROM scrape_sources WHERE key = 'ocasionplus';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'audi|a3', 'Audi', 'A3', 15, NULL, '{"make_slug":"audi","model_slug":"a3"}', 1 FROM scrape_sources WHERE key = 'flexicar';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'audi|a3', 'Audi', 'A3', 15, NULL, '{"make_id":4,"model_id":345}', 1 FROM scrape_sources WHERE key = 'coches.net';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'audi|a3', 'Audi', 'A3', 15, NULL, '{}', 1 FROM scrape_sources WHERE key = 'ocasionplus';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'mitsubishi|montero', 'Mitsubishi', 'Montero', 15, 'https://irurimotor.com/wp-json/vehica/v1/cars?marca=mitsubishi', '{}', 1 FROM scrape_sources WHERE key = 'irurimotor';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'audi|a3', 'Audi', 'A3', 15, 'https://www.quadis.es/coches/audi/a3', '{"make_id":13,"model_id":37}', 1 FROM scrape_sources WHERE key = 'quadis';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'audi|a4 allroad quattro', 'Audi', 'A4 Allroad quattro', 15, 'https://www.quadis.es/coches?makeId=13&modelId=38', '{"make_id":13,"model_id":38}', 1 FROM scrape_sources WHERE key = 'quadis';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'mercedes|clase a', 'Mercedes', 'Clase A', 15, 'https://www.quadis.es/coches/mercedes-benz/clase-a', '{"make_id":4,"model_id":12}', 1 FROM scrape_sources WHERE key = 'quadis';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'audi|a3', 'Audi', 'A3', 15, 'https://www.compramostucoche.es/comprar-coche/?brand=AUDI&model=AUDI.A3&sort=STANDARD_PRICE_ASC', '{"brand":"AUDI","model_tokens":["A3","A3 SPORTBACK","A3 LIMOUSINE","A3 ALLSTREET"]}', 1 FROM scrape_sources WHERE key = 'compramostucoche';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'audi|a4 allroad quattro', 'Audi', 'A4 Allroad quattro', 15, 'https://www.compramostucoche.es/comprar-coche/?brand=AUDI&model=AUDI.A4%20ALLROAD&sort=STANDARD_PRICE_ASC', '{"brand":"AUDI","model_tokens":["A4 ALLROAD"]}', 1 FROM scrape_sources WHERE key = 'compramostucoche';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'mercedes|clase a', 'Mercedes', 'Clase A', 15, 'https://www.compramostucoche.es/comprar-coche/?brand=MERCEDES_BENZ&model=MERCEDES_BENZ.A-KLASSE&sort=STANDARD_PRICE_ASC', '{"brand":"MERCEDES_BENZ","model_tokens":["A-KLASSE","A-KLASSE LIMOUSINE"]}', 1 FROM scrape_sources WHERE key = 'compramostucoche';
--> statement-breakpoint
INSERT OR IGNORE INTO scrape_targets (source_id, make_model_key, make, model, max_results, search_url, search_params, is_active) SELECT id, 'mitsubishi|montero', 'Mitsubishi', 'Montero', 15, 'https://www.compramostucoche.es/comprar-coche/?brand=MITSUBISHI&model=MITSUBISHI.PAJERO&sort=STANDARD_PRICE_ASC', '{"brand":"MITSUBISHI","model_tokens":["PAJERO"]}', 1 FROM scrape_sources WHERE key = 'compramostucoche';
--> statement-breakpoint
